modLoader="javafml"
loaderVersion="${target_loader}"
issueTrackerURL="https://github.com/IMB11/Fog/issues"
displayURL="https://imb11.dev/"
logoFile="assets/fog/icon.png"
authors="IMB11,Steveplays"
license="All-Rights-Reserved"

[[mods]]
modId="fog"
version="${mod_version}"
displayName="Fog"
description="An expansive and dynamic overhaul to Minecraft's fog rendering system."

[[mixins]]
config="fog.mixins.json"

[[dependencies.fog]]
modId="${loader}"
${mandatory_inclusion_field}
versionRange="${target_loader}"
ordering="NONE"
side="BOTH"

[[dependencies.fog]]
modId="minecraft"
${mandatory_inclusion_field}
versionRange="${target_minecraft}"
ordering="NONE"
side="BOTH"

[[dependencies.fog]]
modId="mru"
${mandatory_inclusion_field}
versionRange="[${target_mru},)"
ordering="NONE"
side="BOTH"

[[dependencies.fog]]
modId = "architectury"
${mandatory_inclusion_field}
versionRange = "*"

[[dependencies.fog]]
modId = "yet_another_config_lib_v3"
${mandatory_inclusion_field}
versionRange = "[3.6.2,)"

[[dependencies.fog]]
modId = "architectury"
${mandatory_inclusion_field}
type="incompatible"
versionRange = "15.0.1"
